version: '3.8'

services:
  immich_power_tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
