name: Build and Tag Docker Image on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract PR number
        id: pr-number
        run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build --build-arg VERSION=pr-${{ env.PR_NUMBER }} \
          -t ghcr.io/${{ github.repository }}:pr-${{ env.PR_NUMBER }} .
